# Basic
name:               "Doctor Who"
description:        "A personal blog"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                ""

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:        "Profile"
    href:           "/profile"
# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

#gems:
#  - jekyll-seo-tag

gems: [jekyll-timeago]

 # This will require each of these plugins automatically.

### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  gray:
    light: '#e3e3e3'
    dark: '#e3e3e3'
  blue:
    light: '#3c9eec'
    dark: '#49a7e9'
  green1:
    light: '#9ee874'
    dark: '#9ee874'
  green:
    light: '#c4f1ab'
    dark: '#c4f1ab'
  purple:
    light: '#c869bf'
    dark: '#c869bf'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
  sepia-bg:
    light: '#704214'
    dark: '#704214'
  sepia-ft:
    light: '#f3eacb'
    dark: '#f3eacb'
  midnight-blue:
    light: '#012345'
    dark: '#012345'
  yellow:
    light: '#FFFF00'
    dark: '#FFFF00'